require: rubocop-rspec

AllCops:
  Exclude:
    - spec/spec_helper.rb

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - lib/findjobs/cli.rb

Metrics/MethodLength:
  Exclude:
    - lib/findjobs/cli.rb
