require 'bundler/setup'
require 'commander'
require 'feedjira'
require 'virtus'
require 'colorize'
require 'celluloid/current'
require 'celluloid/pmap'

require 'findjobs/version'
require 'findjobs/job'
require 'findjobs/providers'
require 'findjobs/finder'
require 'findjobs/cli'
